# FILES
defaults: # (these specify which config FILES to use)
  ############## TRAIN ###################################
  - train/config: splade
  - train/data: distil_from_ensemble
  - train/model: splade
  ############## INDEX ###################################
  - index: msmarco
  ############## RETRIEVE ################################
  - retrieve_evaluate: all
  ############### FLOPS ##################################
  - flops: msmarco

# Direct PARAMETER setting
config:
  loss: DistilMarginMSE
  regularizer:
    FLOPS:
      lambda_q: 0.1
      lambda_d: 0.08
      T: 50000
      targeted_rep: rep
      reg: FLOPS
  checkpoint_dir: models/ensemble_distil/checkpoint
  index_dir: models/ensemble_distil/index
  out_dir: models/ensemble_distil/out